# Generated by Django 3.0.5 on 2020-12-29 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EndClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryApp.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(verbose_name='Date')),
                ('address', models.CharField(default='Address not found', max_length=100000)),
                ('Product_cost', models.DecimalField(decimal_places=5, default=0.0, max_digits=30)),
                ('Delivery_cost', models.DecimalField(decimal_places=5, default=0.0, max_digits=30)),
                ('Status', models.CharField(choices=[('paid', 'PAID'), ('pending', 'PENDING'), ('sent', 'SENT')], default='pending', max_length=99)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryApp.Client')),
                ('delivery_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryApp.Delivery_In')),
                ('delivery_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryApp.Delivery_Out')),
                ('end_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryApp.EndClient')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryApp.Manager')),
            ],
        ),
    ]
